# app/repositories/interfaces.py
from typing import Protocol, List, Optional
from app.models import Alumno

class IAlumnoRepository(Protocol):
    def crear(self, alumno: Alumno) -> None: ...
    def buscar_por_id(self, id: int) -> Optional[Alumno]: ...
    def buscar_todos(self) -> List[Alumno]: ...
    def actualizar(self, alumno: Alumno) -> Alumno: ...
    def borrar_por_id(self, id: int) -> Optional[Alumno]: ...
